### ISSUE TITLE
Add argument to run-r-scripts, with default to "TestPortfolio_Input"

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/PACTA_analysis#146] opened 2020-10-09 13:42 UTC
Right now the script `run-r-scripts` hard-wires "TestPortfolio_Input". This should be an argument.

**Comment by cjyetman** [comment] 2020-10-21 08:58
closing as duplicate of #176

**Closed by cjyetman** 2020-10-21 08:58 UTC
Labels: enhancement
