### ISSUE TITLE
Get input files fails with () in investor or portfolio name

### ISSUE THREAD

**Issue by Clare2D** [2DegreesInvesting/PACTA_analysis#418] opened 2021-03-05 10:01 UTC
https://github.com/2DegreesInvesting/PACTA_analysis/blob/42e53f8204dcf065cc9778f7671bc1de6ccf9c99/0_web_functions.R#L108

The line 117 in the 0_web_functions fails if there is a parenthesis in the investor name column. I assume this may also be the case for other special characters. Either we need to ensure that these don't get this far, or alter the function here.

**Comment by cjyetman** [comment] 2021-03-05 10:37
https://github.com/2DegreesInvesting/PACTA_analysis/blob/42e53f8204dcf065cc9778f7671bc1de6ccf9c99/0_web_functions.R#L117

L117 only lists the filenames... do you mean the parenthesis is in the filename, or is it possible the error is at a different line?

**Comment by Clare2D** [comment] 2021-03-05 10:39
sorry L122

**Comment by cjyetman** [comment] 2021-03-05 10:46
I don't get any errors with this...
``` r
library(tidyverse)
library(fs)
portfolio_name_ref_all <- "TestPortfolio_Input"
project_location <- "working_dir"
par_file_path <- "working_dir/10_Parameter_File"
grouping_variables <- c("investor_name", "portfolio_name")

portfolio_path <- file.path(project_location, "20_Raw_Inputs", "TestPortfolio_Input.csv")
read_csv(portfolio_path) %>% 
  mutate(
    Portfolio.Name = "portfolio_name",
    Investor.Name = "investor(name)"
  ) %>% 
  write_csv(portfolio_path)

source("0_global_functions.R")
source("0_portfolio_input_check_functions.R")
source("0_web_functions.R")

grouping_variables <- c("investor_name", "portfolio_name")
get_input_files(portfolio_name_ref_all)

grouping_variables <- c("investor_name")
get_input_files(portfolio_name_ref_all)

grouping_variables <- c("portfolio_name")
get_input_files(portfolio_name_ref_all)

grouping_variables <- c()
get_input_files(portfolio_name_ref_all)
```

**Comment by cjyetman** [comment] 2021-03-05 10:47
> sorry L122

heh? that's also only dealing with filenames
https://github.com/2DegreesInvesting/PACTA_analysis/blob/42e53f8204dcf065cc9778f7671bc1de6ccf9c99/0_web_functions.R#L122

**Comment by cjyetman** [comment] 2021-03-05 10:50
because of these lines, it actually doesn't matter what `Investor.Name` or `Portfolio.Name` is (or if they even exist), because they're both overwritten anyway
https://github.com/2DegreesInvesting/PACTA_analysis/blob/42e53f8204dcf065cc9778f7671bc1de6ccf9c99/0_web_functions.R#L174-L180

**Comment by Clare2D** [comment] 2021-03-05 10:55
Ah then in the filename itself. I think however that this is not possible to upload a parenthesis file name, and it just occurs because I'm creating it manually... Perhaps this is a non issue and I just need to save the file differently.

**Comment by cjyetman** [comment] 2021-03-05 11:12
🤷🏻 color me flabbergasted
``` r
temp_dir <- tempdir()
file.copy(from = "working_dir/20_Raw_Inputs/TestPortfolio_Input.csv",
          to = file.path(temp_dir, "Test(Portfolio)_Input.csv"))
#> [1] TRUE
list.files(temp_dir)
#> [1] "rs-graphics-202627b5-f8e4-41a1-8fed-bf0bc9207e91"
#> [2] "Test(Portfolio)_Input.csv"     

input_path <- temp_dir
portfolio_name_ref_all <- ""

list.files(path = input_path, full.names = F) 
#> [1] "rs-graphics-202627b5-f8e4-41a1-8fed-bf0bc9207e91"
#> [2] "Test(Portfolio)_Input.csv"   

unique(tools::file_ext(grep(portfolio_name_ref_all, list.files(path = input_path, full.names = F), value = T))) 
#> [1] ""    "csv"

portfolio_name_ref_all <- "Test(Portfolio)_Input"

unique(tools::file_ext(grep(portfolio_name_ref_all, list.files(path = input_path, full.names = F), value = T))) 
#> logical(0)
```

If `portfolio_name_ref_all` contains a parenthesis, L122 might return a zero length vector, but it shouldn't give an error. That's probably because the string assigned to `portfolio_name_ref_all` is being interpreted/used as a regex by `grep()`. Doesn't that give any clue?

**Comment by cjyetman** [comment] 2021-03-05 11:37
And sorry, I got off track... we were not looking for errors, we were looking for "failure"... so yes indeed, if `portfolio_name_ref_all` contains a parenthesis, which would imply that the portfolio name/s in the data and probably/possibly also in the filename also have a parenthesis, then `get_input_files()` will likely be unable to determine the input files extension, and therefore will fail.... and that is directly caused by L122 because it interprets/uses the string contained by `portfolio_name_ref_all` as a regex, and parenthesis as well as other characters have special meanings in regex.

https://github.com/2DegreesInvesting/PACTA_analysis/blob/42e53f8204dcf065cc9778f7671bc1de6ccf9c99/0_web_functions.R#L122

reopening because this is something that could surely be fixed/improved

**Comment by Clare2D** [comment] 2021-03-05 13:41
Yep exactly. If you can find a solution for this, that would be great!

**Comment by cjyetman** [comment] 2021-03-05 14:19
my quick guess would be to add `fixed = TRUE` to the `grep()` command, which should treat the pattern "as-is"... but we should put that to the test

**Closed** 2021-03-09 09:43 UTC
Labels: bug
