### ISSUE TITLE
ensure that devtools is installed in 1_portfolio_check_initialization

### ISSUE THREAD

**Issue by andybue** [2DegreesInvesting/PACTA_analysis#466] opened 2021-07-02 09:36 UTC
One of the first comments of the script (in line6) is:

`devtools::load_all()`

In the collobartion with Sweden,  we tried to run the code offline.  we realized, that, if devtools, it not installed, the code does not return explicitly, that devtools is not installed, but complains about missing function in a later points.

It would be great, if a line is added, that asserts that devtools is installed, and either direclty installs it or suggests to install it before line6

**Comment by cjyetman** [comment] 2021-07-02 10:49
While I sympathize with the intent here, there are many required packages for PACTA to run beyond just `devtools`. See for instance https://github.com/2DegreesInvesting/PACTA_analysis/blob/master/deduplicate/load-and-attach-r-packages.R

So if any such assertions should be made, it should probably be for a full list of required packages.

Also of note... as long as this repo is not fully transformed into a true package (which would then manage all these things in a more automatic way), I would love to rip out all this developer/package style stuff because I think it just way over-complicates things, e.g. using `devtools` to load scripts in the `R/` directory, this weird `deduplicate/` directory with some other utility functions, these deeply nested utility functions that you have to follow down 3 or 4 levels before you can figure out what it is actually doing, etc.

**Comment by AlexAxthelm** [comment] 2021-07-02 14:29
I agree with CJ on this point. we've not prioritized making this into a package, which would take care of a lot of these concerns for us. If we're planning on having more users running this on their own in the future, then we can reprioritize that, but that would be a pretty big chunk of work. 

Since this package iis under active development, keeping track of the dependencies is not impossible, but it could get tricky. Installing common packages is a pretty common issue when working in R, so I'd expect users who have installed software that's still in development to be used to this kind of issue.

**Comment by cjyetman** [comment] 2021-07-02 23:03
Also, after thinking about this more.... I suspect that what's happening is that the people are selecting portions of the code in the editor and clicking run or command-enter, which means an "assertion" will not stop this problem either. The call to a function that is not in scope because the package is not installed should already serve the purpose of an assertion, because it too will cause an error and halt if the script is run as a complete script, e.g. using `source()`. But it's a very common problem that R users manually run chunks of code from the editor, and the problem is that RStudio will run each selected line in sequence regardless of whether the previous line errors or not, so a failed assertion will also not prevent the following lines from running, which causes a lot of confusion when people don't realize that. I even wrote a package to deal with this problem: https://github.com/cjyetman/safe.run

@andybue do you understand what I'm saying here? Do you think I'm guessing right here, or is this off base?

**Comment by andybue** [comment] 2021-07-03 10:14
Thanks @cjyetman  and @AlexAxthelm 

well it is true that the current version of the code is far from an ideal state, that allows users to run it completly autonomous. And I get, that fixing this tiny part, while letting all the rest of the code like it is doesn't really make a difference. 

For me, the major inconsistancy, even in the current state is, that somebody had the idea to use
devtools::load_all()
to load all necessary packages, which appears kind of clean. following this comment, even leads to a quite complete list of necessary packages to run the code, which is also great.  But, the list actually is not the complete list of packages need to run the code, as devtools is also needed. 
 
running devtools::load_all() does not throw an error if devtools is not installed, so i thought everything went well, all packages are loaded and he went on... and then just later the code complaied that "use_r_packages" is undefined. and he could not figure out the reason, because he assumed that  devtools::load_all()  sourced all packages...

Jacob and me found the bug within 2 min, and then he installed devtools... he probably would have been able to run the code himself, if there would be any indication that devtools actually needs to be installed. maybe it was a really specific issue of this guy that is not to familiar with R. However, Me and @jacobvjk had the impression that there should be an indication (does not necessarly have to be an assertation check) that devtools needs to be installed.

I wanted to report this observation, but I'm pretty agnostic the way forward as long as we do not forget, that mid-term there should be a work-flow for using the investors code from github without me and jacob on the phone. So ok for me, to not fix it now, but do a major review of the workflow until the end of the year.

**Comment by AlexAxthelm** [comment] 2021-07-03 16:00
I agree that giving users the tools they need to run things without our help is important. 

And I'm glad that it's not a super urgent item, since the only good way to move forward is to implement proper dependency management (and package-ize this code). That's basically the only solution I'm willing to consider to this problem, since I've tried other solutions in the past, and they all ended up  making more work than they solved. `R`'s package management isn't perfect, but it's better than trying to reinvent it ourselves. Opened AB#765 to track on ADO

**Comment by cjyetman** [comment] 2021-09-16 08:57
circling back to this...

an example of what I'm saying, if you select this code in RStudio/ R GUI and run it, you'll get...
``` r
stopifnot(require(XXX))
#> Loading required package: XXX
#> Warning in library(package, lib.loc = lib.loc, character.only = TRUE,
#> logical.return = TRUE, : there is no package called 'XXX'
#> Error: require(XXX) is not TRUE
print("didn't stop")
#> [1] "didn't stop"
```

So even though there is an assertion that package `XXX` must exist and the `stopifnot()` throws an error because it doesn't, the rest of the code will continue to run. There's no way around that because that's how the RStudio and the R GUI interface work.... if you select a bunch of code and tell it to run it, it will run each line of code progressively regardless of whether any of those lines result in an error. If you **source** that code from a script, it will throw an error and stop. I even [built a package to override this behavior in the GUI](https://github.com/cjyetman/safe.run) because I think it's annoying and confusing... but that only works if you preinstall the package and set it up to override the normal "run selected code" key command.

I think the only option here would be.... since in order to have the code, they must have cloned our repo, we could potentially use `renv` or a similar package library management system to force them to use the same packages and same package versions that we depend on. I'm actually in favour of that option, but it's a bit of a large project to achieve.

**Comment by cjyetman** [comment] 2021-11-29 15:13
related issue #525

**Comment by cjyetman** [comment] 2021-11-29 15:22
> running devtools::load_all() does not throw an error if devtools is not installed

Also, I don't see how this could be possible.
```r
devtools::load_all()
#> Error in loadNamespace(x) : there is no package called ‘devtools’
```

**Comment by AlexAxthelm** [comment] 2021-11-29 19:53
Suggestion: what if we move away from needing `devtools::load_all`, and instead use R's normal package management?

**Comment by jdhoffa** [comment] 2021-11-29 21:16
> Suggestion: what if we move away from needing `devtools::load_all`, and instead use R's normal package management?

A (very lengthy) discussion related to that suggestion can be found [here](https://github.com/2DegreesInvesting/PACTA_analysis/pull/514#issuecomment-975615331). 

I back it, but there are some considerations worth... considering.

**Comment by cjyetman** [comment] 2021-11-29 21:37
> Suggestion: what if we move away from needing `devtools::load_all`, and instead use R's normal package management?

what is R's normal package management?

**Comment by AlexAxthelm** [comment] 2021-11-30 08:32
the short version is: 
* put all the code in `R/`
* use `export` to determine what is a public function (`package::function()` vs `package:::function()`)
* use `DESCRIPTION` to define dependencies
* don't use `library()` anywhere.

**Comment by cjyetman** [comment] 2021-11-30 08:57
Ah... but that breaks existing code in other repos and very likely places we don't know or understand, so I'm always avoiding it.

**Comment by AlexAxthelm** [comment] 2021-11-30 09:07
I'm very much on "team package, even if other code needs to adapt to it." Code is a living document, and I don't think we should restrict ourselves to bad solutions. We can provide workarounds and deprecation notices, but we should make sure that we can keep our own house in order.

I'm imagining something like:
```r
source("web_tool_script_1.R")
```
```
Warning message:
web_tool_script_1 will be deprecated on 2022-06-31. Please call PACTA.analysis::audit_portfolio() instead. 
```

**Comment by AlexAxthelm** [comment] 2021-11-30 09:08
basically, as part of refactor, we keep the code in places that people expect, but give them a warning that it will be moving.

**Comment by jacobvjk** [comment] 2021-11-30 09:29
if you need any changes from us on the ST side for this, please shout. More than happy to adapt the scripts to handle this

**Comment by AlexAxthelm** [comment] 2021-11-30 09:32
don't worry, @jacobvjk. The change I'm talking about will (eventually) be a big change, and we'll give you plenty of time to adapt.

**Comment by cjyetman** [comment] 2021-11-30 10:07
> I'm very much on "team package, even if other code needs to adapt to it." Code is a living document, and I don't think we should restrict ourselves to bad solutions. We can provide workarounds and deprecation notices, but we should make sure that we can keep our own house in order.

There's nothing wrong or "bad" about having R code not in a package structure. We could just as easily solve the problem by taking all of the functions that currently live in `R/` and putting them back into `0_global_functions.R` where those things used to live before we forced a half-hearted attempt to make it a package. This problem only exist because of that change.

We could also simply replace `devtools::load_all()` with something like `sapply(list.files("R", "[.]R$", full.names = TRUE), source)`. This is the point I'm trying to make.... committing to making this repo a package seriously restricts what we can do, forces us to use specific tools, forces us to comply to a structure that doesn't necessarily make sense for us, all of which so far has caused more headaches than benefit as far as I can tell. Everything that we want from these tools is easily replaceable, and the vast majority of what they do is irrelevant here.

For the record, I think it's a very bad idea, especially without a very complete, very specific list of expectations for what PACTA can/does do.

**Comment by cjyetman** [comment] 2021-12-30 11:36
Closing this in favor of #525 which is the only real way that I know of to force a user to have the necessary packages installed when using this repo in the way that it is currently intended to be used. Even if all dependencies for all use cases are explicitly and exclusively listed in the DESCRIPTION file, that still does not enforce that all those packages will be installed, unless and until a user has installed this repo as a package, either locally with developer tools (which I believe is unlikely) or from CRAN which is either a long way off or never going to happen. Additionally, as I've explained above and given examples of, if a user selects a bunch of lines of code and runs them in the R GUI or in RStudio, there is absolutely no way possible to error out and stop execution of the lines that follow a `library()` or `require()` call that fail because the package is not installed.

**Closed by cjyetman** 2021-12-30 11:36 UTC
Labels: bug
